services:
    trading_helper_web_service:
        image: trading_helper_web
        container_name: trading_helper_web_service
        depends_on:
            - metatrader5_api_service
        volumes:
            - ../trading_helper_web:/usr/src/app/trading_helper_web
            - ../.env:/usr/src/app/.env
        working_dir: /usr/src/app
        command: [
            "bash", "-c",
            "python3 trading_helper_web/manage.py migrate && 
             python3 trading_helper_web/manage.py runserver 0.0.0.0:8000"
        ]
        ports:
            - "127.0.0.77:80:8000"  # Match this localhost ip to domain name (change /etc/hosts file).

    metatrader5_api_service:
        image: metatrader5_api
        container_name: metatrader5_api_service
        volumes:
            - ../metatrader5_api/server:/server
            - ../.env:/.env
        ports:
            - "3000:3000"
            - "8080:8080"
